on:
  push:
    branches: [build]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1.6.0

      - name: Install Lucky
        run: |
          cd /tmp
          git clone https://github.com/luckyframework/lucky_cli
          cd lucky_cli
          shards install
          shards build
          mv bin/lucky /usr/local/bin/

      - name: Build
        run: |
          echo "Removing build specific files"
          rm -f .github/workflows/build.yml

          echo "🔮Initializing via: lucky init"
          lucky init.custom horseshoe

          echo "Merging template with shard init"
          mkdir -p .install
          mv horseshoe/README.md .install/README.md
          cp -rn horseshoe/* .
          cp -rn horseshoe/.?* .
          rm -rf horseshoe/

          sed -i '/^development_dependencies:/i \ \ ameba:\n\ \ \ \ github: crystal-ameba/ameba' shard.yml

      - name: Push Build to Main
        run: |
          git config --global user.email "alex@piechowski.io"
          git config --global user.name "Alex Piechowski"
          git add .
          git commit -am "Build: This commit will be overwritten upon template creation"
          git push -f origin build:main
