#!/usr/bin/env bash

set -e

only_repo=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
new_snek_name=$(echo $only_repo | sed 's/-/_/g' | sed 's/\./_/g')

echo "🔮Initializing via: lucky init"
lucky init.custom $new_snek_name

echo "Merging template with lucky init"
cp $new_snek_name/README.md .
cp -rn $new_snek_name/* .
cp -rn $new_snek_name/.?* .
rm -rf $new_snek_name/

echo "Replacing Laravel Mix with esbuild"
rm -f src/js/app.js
sed -i 's/Lucky::AssetHelpers.load_manifest "public\/mix-manifest.json"/Lucky::AssetHelpers.load_manifest "public\/manifest.json"/g' src/app.cr

echo "Touching up app to work with docker postgres"
sed -i '/^lucky db.create/i docker-compose up -d postgres' script/setup
sed -i 's/horseshoe/'$new_snek_name'/g' docker-compose.yml

echo "Adding changes to shard.yml"
sed -i '/^development_dependencies:/i \ \ ameba:\n\ \ \ \ github: crystal-ameba/ameba' shard.yml
sed -i "s/${new_snek_name}:/app:/" shard.yml

echo "Fixing ameba violation 😳"
# TODO: Remove after https://github.com/luckyframework/lucky_cli/pull/739 is released
sed -i '49,58d' config/server.cr

echo "Removing install specific files"
rm -f .github/workflows/install.yml
rm -f .github/workflows/install
